ДЗ 11: Клиент TELNET
iantropov/otus-golang pull request #11
Opened 2023-03-16 04:10 UTC by iantropov

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2023-03-19 07:45 UTC, vladislavmass requested changes
Работа как обычно хорошая. Радует что написано много тестов. Насколько я помню os.Interrupt обрабатывает, только Ctrl+C. Обработка Ctrl+D в коде отсутствует. Также рекомендую почитать про io.copy. Пока работу принять не могу.

2023-03-19 07:45 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	return fmt.Sprintf("%s:%s", connectionArgs[0], connectionArgs[1]), nil
Для такой цели можно еще использовать net.JoinHostPort.

2023-03-19 07:45 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	bufferOut := &bytes.Buffer{}
Не совсем понимаю зачем нужны буферы, если можно сразу через io.copy скопировать в консоль.

2023-03-19 07:45 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +		time.Sleep(time.Second)
Я бы предложил заменить это на либо на канал, либо на мьютекс. Но лучше на канал.

2023-03-22 07:37 UTC, iantropov commented on hw11_telnet_client/main.go
> +	bufferOut := &bytes.Buffer{}
Да, через io.Copy гораздо лучше!

2023-03-22 07:37 UTC, iantropov commented on hw11_telnet_client/main.go
> +	return fmt.Sprintf("%s:%s", connectionArgs[0], connectionArgs[1]), nil
Точно, спасибо!

2023-03-22 07:38 UTC, iantropov commented
> Обработка Ctrl+D в коде отсутствует

Обработка происходит как EOF для os.Stdin.

2023-03-23 04:28 UTC, vladislavmass commented
> > Обработка Ctrl+D в коде отсутствует
> 
> Обработка происходит как EOF для os.Stdin.

Я бы конечно рекомендовал это сделать через сигнал SIGQUIT, но ок.

2023-03-23 04:38 UTC, vladislavmass approved these changes
Так гораздо лучше. Работа принята. 9/10.  -1 бал за лишний в данном случае канал и некорректное закрытие горутин.

2023-03-23 04:38 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +		res <- telnetClient.Send()
Более правильным вариантом было бы в случае ошибки дернуть cancel и сделать return. А также  сделать ожидание сообщения либо из  `telnetClient.Send()`, либо `ctx.Done`.

2023-03-23 06:33 UTC, iantropov commented
Владислав, насколько я [понимаю](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html), SIGQUIT - это про `ctrl + \`, а для `ctrl + D` отдельного сигнала нет, так как это [спец. символ EOF/EOT](https://en.wikipedia.org/wiki/End-of-Transmission_character)

2023-03-23 06:40 UTC, iantropov commented on hw11_telnet_client/main.go
> +		res <- telnetClient.Send()
Напрямую сделать `select` для `telnetClient.Send()` и `ctx.Done` не получилось, поскольку функция `Send()` не работает с каналами. Но остальное - переделал.

2023-03-23 06:55 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +		res <- telnetClient.Send()
Да, согласен.

2023-03-23 06:55 UTC, vladislavmass approved these changes
Оценка повышены.10/10

2023-03-24 02:34 UTC, merged