ДЗ 3: Частотный анализ
iantropov/otus-golang pull request #3
Opened 2022-12-22 06:40 UTC by iantropov

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-22 13:53 UTC, vladislavmass requested changes
Работа хорошая. Хорошо что добавили новые тесты. В коде есть несколько опечаток и одна недоработка. Поэтому работа принять не могу.

2022-12-22 13:53 UTC, vladislavmass commented on hw03_frequency_analysis/go.mod
> +module github.com/iantropov/otus-lang/hw03_frequency_analysis
Неверное имя модуля. С таким именем go get работать не будет.

2022-12-22 13:53 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	sortedWords := make([]string, len(frequencies))
Забивать слайс значением по умолчанию в случае со строкой не самая хорошая затея. Предлагаю создать массив с заранее известным капасити а не длинной.

2022-12-22 13:53 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return sortedWords[:wordsCount:wordsCount]
Тут явная опечатка.

2022-12-23 08:32 UTC, iantropov commented on hw03_frequency_analysis/top.go
> +	sortedWords := make([]string, len(frequencies))
А какие варианты? Сделать 0ю длину и на каждой итерации добавлять append-ом? Если уж экономим на спичках, то вызов append далеко не пара инструкций - https://github.com/golang/go/blob/go1.16.7/src/cmd/compile/internal/gc/ssa.go#L2841... 

Почему вы думаете, что ваш вариант будет производительнее? Замеры показывают обратное (сверху мой вариант, снизу - ваш):

<img width="741" alt="image" src="https://user-images.githubusercontent.com/511114/209301413-2ca7f627-e759-4f88-87cc-cc096f7006c7.png">

2022-12-23 08:32 UTC, iantropov commented on hw03_frequency_analysis/go.mod
> +module github.com/iantropov/otus-lang/hw03_frequency_analysis
Почему неверное имя? В прошлой домашке такое же было...

2022-12-23 08:32 UTC, iantropov commented on hw03_frequency_analysis/top.go
> +	return sortedWords[:wordsCount:wordsCount]
Почему опечатка? Я делаю слайс c len и cap равными wordsCount.

2022-12-23 12:54 UTC, vladislavmass commented on hw03_frequency_analysis/go.mod
> +module github.com/iantropov/otus-lang/hw03_frequency_analysis
видимо в тот раз не заметил. Имя репозитария otus-golang

2022-12-23 13:52 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	sortedWords := make([]string, len(frequencies))
У меня показатели говорят как раз таки обратное. 

![Снимок экрана 2022-12-23 163238](https://user-images.githubusercontent.com/74667007/209344468-4ad71542-4a8f-4571-8172-7a9ab411c47a.png)

Это с append
![22223](https://user-images.githubusercontent.com/74667007/209344735-71030c07-ae73-4075-9b8a-96e3fe401864.png)

Это вариант из репозитария.

По сути разница на уровне погрешности.

2022-12-23 13:52 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return sortedWords[:wordsCount:wordsCount]
Я понимаю что речь идет о лен и кап. И я понимаю что тут идет обрезка при передачи, что бы не передавать лишнее. Но я бы рекомендовал использовать copy. Так как даже  при текущем варианте вернется все ровно ссылка на начало старого массива и переменная куда мы ее запишем будет занимать больше места чем могла бы.

2022-12-24 09:27 UTC, iantropov commented on hw03_frequency_analysis/top.go
> +	return sortedWords[:wordsCount:wordsCount]
Поправил.

2022-12-24 09:27 UTC, iantropov commented on hw03_frequency_analysis/go.mod
> +module github.com/iantropov/otus-lang/hw03_frequency_analysis
Охх, вы правы! Спасибо, поправил.

2022-12-24 15:48 UTC, HangryHoneyBadger approved these changes
Работа принята. 10/10

2022-12-24 15:49 UTC, vladislavmass approved these changes
Работа принята. 10/10

2022-12-29 04:54 UTC, merged