Домашнее задание №5 «Параллельное исполнение»
iantropov/otus-golang pull request #5
Opened 2023-01-21 02:40 UTC by iantropov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-21 22:02 UTC, vladislavmass requested changes
Приятно удивило количество новых тестов. Решение не соответствует задаче. По заданию за все время работы программы не может быть запущено больше чем n горутин, а данная реализация контролирует число одновременно запущенных горутин.

2023-01-22 19:20 UTC, vladislavmass requested changes
Работа не решает поставленной задачи. Поэтому принять не могу.  Рекомендую для воркера использовать select, а для остановки рекомендую смотреть в сторону context.WithCancel.

2023-01-22 19:20 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +	taskChannel := make(chan Task, len(tasks))
Не слишком ли большой объем буфера. Если по сути вначале вычитываются n задач из буфера, после чего в буфер попадает по 1 задаче. И получается что буфер может быть на тысячи задачи, при том что потоков всего 5-6.

2023-01-22 19:20 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		ok := <-okChannel
Так конечно работает, но в данном случае если канал будет закрыт, то из канала будет каждый раз удачно считываться дефолтное значение. Поэтому я бы рекомендовал заменить этот цикл, на цикл вида for ok := range okChannel

2023-01-22 19:20 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		task := <-taskChannel
Так конечно работает, но в данном случае если канал будет закрыт, то из канала будет каждый раз удачно считываться дефолтное значение. Поэтому я бы рекомендовал заменить этот цикл, на цикл по каналу.

2023-01-22 19:20 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	if m > n {
Я понимаю зачем это надо, но это явно неправильный подход.  Не надо ограничивать число ошибок числом потоков.

2023-01-24 20:34 UTC, vladislavmass approved these changes
Как всегда хорошая работа. Приятно удивило количество новых тестов. Код немного избыточен, но это не является какой то проблемой. оценка 10/10

2023-01-24 20:34 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	okChannel := make(chan bool, n)
Единственное наверное с чем несогласен. Я бы наверное назвал его скорее ErrChanel, так как интересуют нас все же ошибки.

2023-01-25 10:41 UTC, iantropov commented on hw05_parallel_execution/run.go
> +	okChannel := make(chan bool, n)
Согласен, так логичнее.

2023-01-25 10:41 UTC, merged