ДЗ 8: «Утилита envdir»
iantropov/otus-golang pull request #8
Opened 2023-02-18 13:08 UTC by iantropov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-02-19 07:21 UTC, vladislavmass requested changes
Работа хорошая, но есть пара замечаний

2023-02-19 07:21 UTC, vladislavmass commented on hw08_envdir_tool/go.mod
>  module github.com/fixme_my_friend/hw08_envdir_tool
Неверное имя модуля

2023-02-19 07:21 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	envValue.Value = strings.TrimRight(string(firstLine), " \t")
А если в конце строки нет табуляция, то код не сработает и пробел останется или например после табуляции может быть еще пробел

2023-02-20 06:40 UTC, iantropov commented on hw08_envdir_tool/go.mod
>  module github.com/fixme_my_friend/hw08_envdir_tool
Вот жеж, вот чуял, что что-то забыл )

2023-02-20 06:44 UTC, iantropov commented on hw08_envdir_tool/env_reader.go
> +	envValue.Value = strings.TrimRight(string(firstLine), " \t")
Не совсем так. Как вы описали - так работает TrimSuffix. TrimRight же чистит все символы из переданной строки в качестве cutset-а. Можете убедиться сами - https://go.dev/play/p/YYruOGG7iqw

2023-02-22 08:57 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	envValue.Value = strings.TrimRight(string(firstLine), " \t")
Согласен.

2023-02-22 08:57 UTC, vladislavmass approved these changes
Работа принята. 10/10

2023-02-22 09:32 UTC, merged